import type { LeafMetricKey } from "./metrics";

/** Per-neighbourhood properties carried in the GeoJSON `properties`. */
export interface NeighbourhoodProperties {
  // City of Toronto schema: the area name lives in AREA_NAME.
  AREA_NAME: string;
  AREA_SHORT_CODE?: string | number;
  // Per-leaf-metric sub-scores (0–100). Generated by mockScores.ts for the
  // sample dataset; replaced by real derived scores in the pipeline.
  scores?: Record<LeafMetricKey, number>;
  // Census characteristics.
  census?: {
    population: number;
    pop_density: number;
    low_income_prop: number;
    children_under15_prop: number;
  };
  // Representative centroid [lon, lat] for routing stubs.
  centroid?: [number, number];
}

export type Position = [number, number];

export interface NeighbourhoodFeature {
  type: "Feature";
  properties: NeighbourhoodProperties;
  geometry: {
    type: "Polygon" | "MultiPolygon";
    coordinates: number[][][] | number[][][][];
  };
}

export interface NeighbourhoodCollection {
  type: "FeatureCollection";
  features: NeighbourhoodFeature[];
}

export type TravelMode = "walk" | "bike" | "drive" | "transit" | "any";

export type PlaceBehavior = "rank" | "click";

export interface PlaceRow {
  id: string;
  /** Free-text target — address/anchor or amenity keyword. */
  target: string;
  mode: TravelMode;
  /**
   * Optional. "rank" = anchor ranks the map; "click" = amenity shown in click
   * detail. Info-only place variants leave this undefined; the Variant C score
   * switch treats commute rows as anchors regardless of this field.
   */
  behavior?: PlaceBehavior;
  /** Optional opt-in hard filter cap, in minutes. */
  underMinutes?: number;
  /** Optional display name for the row (e.g. "Zach's Work"). */
  label?: string;
}
