import fs from "node:fs";
import path from "node:path";
import { NextResponse } from "next/server";
import {
  METRIC_EXAMPLE_DEFS,
  type MetricExampleDef,
} from "@/lib/metricExamples";
import type { LeafMetricKey } from "@/lib/metrics";
import { addressFrom, overpassQuery } from "@/lib/overpassServer";
import { ENRICHED_PROGRAMS } from "@/lib/enrichedPrograms";
import {
  googleLooksDead,
  markGoogleAlive,
  markGoogleDead,
} from "@/lib/googleKeyHealth";

// Real per-metric example places for the detail panel.
//   1. Google Places text search per metric (when a working key exists) —
//      returns star ratings, review counts, and real listing links.
//   2. PRECOMPUTED data from public/data/metric-examples.json (generated by
//      `node scripts/precompute-examples.mjs`) — instant, no network.
//   3. ONE combined live Overpass query for anything still uncovered.
// POST { bbox: [s,w,n,e], metrics: LeafMetricKey[], area?: AREA_NAME }
// -> { results: { [key]: { count, examples: [...] } } }
export const revalidate = 0;

const EXAMPLES_CAP = 8;
const TEXT_SEARCH_URL = "https://places.googleapis.com/v1/places:searchText";

interface Example {
  name: string;
  address: string | null;
  lat: number;
  lon: number;
  mapsUrl: string;
  rating: number | null;
  reviews: number | null;
}

interface MetricResult {
  count: number;
  examples: Example[];
}

// --- Precomputed ETL data (public/data/metric-examples.json) ---------------

interface PrecomputedFile {
  areas?: Record<string, Record<string, MetricResult>>;
}

const PRECOMPUTED_PATH = path.join(
  process.cwd(),
  "public",
  "data",
  "metric-examples.json",
);

let precomputed: PrecomputedFile | null = null;
let precomputedMtime = 0;

/** Lazy-load the precomputed file, re-reading when it changes on disk. */
function getPrecomputed(area: string): Record<string, MetricResult> | null {
  try {
    const stat = fs.statSync(PRECOMPUTED_PATH);
    if (!precomputed || stat.mtimeMs !== precomputedMtime) {
      precomputed = JSON.parse(
        fs.readFileSync(PRECOMPUTED_PATH, "utf8"),
      ) as PrecomputedFile;
      precomputedMtime = stat.mtimeMs;
    }
    return precomputed.areas?.[area] ?? null;
  } catch {
    return null; // file absent/corrupt — fall through to live sources
  }
}

/** In-memory cache; empty results are not cached. */
const cache = new Map<
  string,
  { ts: number; results: Record<string, MetricResult> }
>();
// POI data changes rarely — long TTL makes revisits instant.
const CACHE_TTL_MS = 6 * 60 * 60 * 1000;

function searchLink(name: string, address: string | null, lat: number, lon: number): string {
  const q = address
    ? `${name}, ${address}`
    : `${name} ${lat.toFixed(5)},${lon.toFixed(5)}`;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
}

function haversineKm(aLat: number, aLon: number, bLat: number, bLon: number): number {
  const R = 6371;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(bLat - aLat);
  const dLon = toRad(bLon - aLon);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(aLat)) * Math.cos(toRad(bLat)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

interface GooglePlace {
  id?: string;
  displayName?: { text?: string };
  rating?: number;
  userRatingCount?: number;
  formattedAddress?: string;
  location?: { latitude?: number; longitude?: number };
  googleMapsUri?: string;
}

/** Google text search within the bbox; null on failure (fallback to OSM). */
async function googleMetric(
  q: string,
  box: { s: number; w: number; n: number; e: number },
): Promise<Example[] | null> {
  const key = process.env.GOOGLE_MAPS_API_KEY;
  if (!key || googleLooksDead()) return null;
  try {
    const res = await fetch(TEXT_SEARCH_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": key,
        "X-Goog-FieldMask":
          "places.id,places.displayName,places.rating,places.userRatingCount," +
          "places.formattedAddress,places.location,places.googleMapsUri",
      },
      body: JSON.stringify({
        textQuery: q,
        maxResultCount: 20,
        locationRestriction: {
          rectangle: {
            low: { latitude: box.s, longitude: box.w },
            high: { latitude: box.n, longitude: box.e },
          },
        },
      }),
      signal: AbortSignal.timeout(10000),
    });
    if (res.status === 401 || res.status === 403) {
      markGoogleDead();
      return null;
    }
    if (!res.ok) return null;
    markGoogleAlive();
    const json = (await res.json()) as { places?: GooglePlace[] };
    const out: Example[] = [];
    for (const p of json.places ?? []) {
      const lat = p.location?.latitude;
      const lon = p.location?.longitude;
      if (typeof lat !== "number" || typeof lon !== "number") continue;
      const name = p.displayName?.text ?? q;
      const address = p.formattedAddress ?? null;
      out.push({
        name,
        address,
        lat,
        lon,
        mapsUrl: p.googleMapsUri ?? searchLink(name, address, lat, lon),
        rating: typeof p.rating === "number" ? p.rating : null,
        reviews:
          typeof p.userRatingCount === "number" ? p.userRatingCount : null,
      });
    }
    return out;
  } catch {
    return null;
  }
}

/** Run async jobs with a small concurrency limit. */
async function withConcurrency<T>(
  jobs: (() => Promise<T>)[],
  limit: number,
): Promise<T[]> {
  const results: T[] = new Array(jobs.length);
  let next = 0;
  async function worker() {
    while (next < jobs.length) {
      const i = next++;
      results[i] = await jobs[i]();
    }
  }
  await Promise.all(
    Array.from({ length: Math.min(limit, jobs.length) }, worker),
  );
  return results;
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as {
      bbox?: [number, number, number, number];
      metrics?: string[];
      area?: string;
    };
    const bbox = body.bbox;
    const area = (body.area ?? "").trim();
    const requested = (body.metrics ?? []).filter(
      (m): m is LeafMetricKey => m in METRIC_EXAMPLE_DEFS,
    );
    if (!bbox || bbox.length !== 4 || requested.length === 0) {
      return NextResponse.json({ results: {} });
    }
    const [s, w, n, e] = bbox;
    if ([s, w, n, e].some((v) => typeof v !== "number" || Number.isNaN(v))) {
      return NextResponse.json({ results: {} });
    }
    const box = { s, w, n, e };
    const cLat = (s + n) / 2;
    const cLon = (w + e) / 2;

    const cacheKey =
      `${s.toFixed(3)},${w.toFixed(3)},${n.toFixed(3)},${e.toFixed(3)}|${area}|` +
      [...requested].sort().join(",");
    const hit = cache.get(cacheKey);
    if (hit && Date.now() - hit.ts < CACHE_TTL_MS) {
      return NextResponse.json({ results: hit.results });
    }

    const results: Record<string, MetricResult> = {};

    // 1. Google Places per metric (star ratings + real listing links).
    const googleable = requested.filter(
      (k) => (METRIC_EXAMPLE_DEFS[k] as MetricExampleDef).googleQuery,
    );
    if (googleable.length > 0) {
      const found = await withConcurrency(
        googleable.map((k) => () =>
          googleMetric(
            (METRIC_EXAMPLE_DEFS[k] as MetricExampleDef).googleQuery as string,
            box,
          ),
        ),
        4,
      );
      googleable.forEach((k, i) => {
        const examples = found[i];
        if (examples && examples.length > 0) {
          examples.sort(
            (a, b) =>
              haversineKm(cLat, cLon, a.lat, a.lon) -
              haversineKm(cLat, cLon, b.lat, b.lon),
          );
          results[k] = {
            count: examples.length,
            examples: examples.slice(0, EXAMPLES_CAP),
          };
        }
      });
    }

    // 2. Precomputed ETL data — instant, no network. Covers whatever Google
    // didn't (no key / dead key / no googleQuery / empty result).
    if (area) {
      const pre = getPrecomputed(area);
      if (pre) {
        for (const key of requested) {
          if (key in results) continue;
          const r = pre[key];
          if (r && typeof r.count === "number") results[key] = r;
        }
      }
    }

    // 3. Live OSM fallback for anything still uncovered — ONE combined
    // Overpass query, classified per metric.
    const remaining = requested.filter((k) => !(k in results));
    if (remaining.length > 0) {
      const selectorSet = new Set<string>();
      for (const key of remaining) {
        const def = METRIC_EXAMPLE_DEFS[key] as MetricExampleDef;
        for (const sel of def.selectors) selectorSet.add(sel);
      }
      const bboxStr = `(${s},${w},${n},${e})`;
      const query =
        `[out:json][timeout:20];(` +
        [...selectorSet].map((sel) => `${sel}${bboxStr};`).join("") +
        `);out center 1500;`;

      const elements = await overpassQuery(query);
      if (elements !== null) {
        for (const key of remaining) {
          const def = METRIC_EXAMPLE_DEFS[key] as MetricExampleDef;
          const seenNames = new Set<string>();
          const matched: (Example & { km: number })[] = [];
          for (const el of elements) {
            const lat = el.lat ?? el.center?.lat;
            const lon = el.lon ?? el.center?.lon;
            if (typeof lat !== "number" || typeof lon !== "number") continue;
            const t = el.tags ?? {};
            if (!def.match(t)) continue;
            if (def.namedOnly && !t.name) continue;
            const nm = t.name ?? def.kindLabel(t);
            if (def.dedupeByName) {
              const k = nm.toLowerCase();
              if (seenNames.has(k)) continue;
              seenNames.add(k);
            }
            const address = addressFrom(t) ?? null;
            matched.push({
              name: nm,
              address,
              lat,
              lon,
              mapsUrl: searchLink(nm, address, lat, lon),
              rating: null, // ratings don't exist in OSM — never fabricate
              reviews: null,
              km: haversineKm(cLat, cLon, lat, lon),
            });
          }
          matched.sort((a, b) => a.km - b.km);
          results[key] = {
            count: matched.length,
            examples: matched.slice(0, EXAMPLES_CAP).map((m) => ({
              name: m.name,
              address: m.address,
              lat: m.lat,
              lon: m.lon,
              mapsUrl: m.mapsUrl,
              rating: m.rating,
              reviews: m.reviews,
            })),
          };
        }
      }
    }

    // 4. Curated enriched programs (TOPS, MaST, IB, arts…) — real programs
    // hosted INSIDE regular schools. Neither OSM (host school's name carries
    // no program signal) nor a dead Google key can surface these, so they're
    // merged from the curated registry whenever they fall inside the bbox.
    if (requested.includes("edu_montessori")) {
      const curated = ENRICHED_PROGRAMS.filter(
        (p) => p.lat >= s && p.lat <= n && p.lon >= w && p.lon <= e,
      ).map((p) => ({
        name: `${p.name} — ${p.school}`,
        address: p.address,
        lat: p.lat,
        lon: p.lon,
        mapsUrl: searchLink(p.school, p.address, p.lat, p.lon),
        rating: null,
        reviews: null,
        km: haversineKm(cLat, cLon, p.lat, p.lon),
      }));
      if (curated.length > 0) {
        curated.sort((a, b) => a.km - b.km);
        const existing = results["edu_montessori"] ?? {
          count: 0,
          examples: [],
        };
        const curatedNames = new Set(
          curated.map((c) => c.name.toLowerCase()),
        );
        const merged = [
          ...curated.map((c) => ({
            name: c.name,
            address: c.address,
            lat: c.lat,
            lon: c.lon,
            mapsUrl: c.mapsUrl,
            rating: c.rating,
            reviews: c.reviews,
          })),
          ...existing.examples.filter(
            (ex) => !curatedNames.has(ex.name.toLowerCase()),
          ),
        ];
        results["edu_montessori"] = {
          count: existing.count + curated.length,
          examples: merged.slice(0, EXAMPLES_CAP),
        };
      }
    }

    if (Object.values(results).some((r) => r.count > 0)) {
      cache.set(cacheKey, { ts: Date.now(), results });
    }
    return NextResponse.json({ results });
  } catch {
    return NextResponse.json({ results: {} });
  }
}
